version : "3"

services:
  redis:
    image: redis:4
    container_name: cloud-redis
    restart: always
    ports:
      - '6379:6379'

  mysql:
    image: mysql:5.7
    container_name: cloud-mysql 
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: [
      "--character-set-server=utf8",
      "--log-bin=mysql-bin",
      "--server-id=1"
    ]

  rabbit:
    image: rabbitmq:3.7-management
    hostname: rabbit
    container_name: "cloud-rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456

networks:
  default:
    driver: bridge