version: '3'
services:

  riverluoo-github:
    container_name: github
    image: registry.cn-shanghai.aliyuncs.com/loo/riverluoo_github:0.1.0
    ports:
      - "80:80"
    restart: always        
  
networks:
  default:
    driver: bridge