version: "3"

services:
  broadcasting-manager:
    container_name: broadcasting-manager
    image: registry.cn-hangzhou.aliyuncs.com/loo/broadcasting-manager:1
    ports:
      - "7777:7777"
    environment:
      - spring.profiles.active=prod
      - spring.datasource.url=jdbc:mysql://172.30.128.9:3306/?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    restart: always

networks:
  default:
    external:
      name: docker-network
      
