version: "3"

services:
  music-manager:
    container_name:music-manager
    image: registry.cn-hangzhou.aliyuncs.com/loo/music-manager:1
    ports:
      - "8090:8090"
    environment:
      - spring.profiles.active=dev
      - spring.datasource.url=jdbc:mysql://127.0.0.1:3306/luoo/?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    restart: always

networks:
  default:
    external:
      name: docker-network
      
