version: '2'

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    volumes:
    - ./minio/data:/data
    ports:
    - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: 
      MINIO_SECRET_KEY: 
    command: server /data

networks:
  default:
    driver: bridge

